# Configuration for PR labeler (actions/labeler@v5)
# Labels PRs based on changed files

tests:
  - changed-files:
    - any-glob-to-any-file: 'test/**/*'

documentation:
  - changed-files:
    - any-glob-to-any-file: '*.md'
  - changed-files:
    - any-glob-to-any-file: 'docs/**/*'

dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - 'package.json'
      - 'package-lock.json'

github-actions:
  - changed-files:
    - any-glob-to-any-file: '.github/workflows/**/*'

extension-core:
  - changed-files:
    - any-glob-to-any-file:
      - 'manifest.json'
      - 'background.js'
      - 'content.js'
      - 'content-utils.js'

ui:
  - changed-files:
    - any-glob-to-any-file:
      - 'options.html'
      - 'options.js'
      - '*.png'
